# Generated by Django 4.0.3 on 2022-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='current_balance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
