# Generated by Django 4.0.3 on 2022-11-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0003_expenses_current_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='current_balance',
        ),
    ]
