# Generated by Django 4.0.3 on 2022-11-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0005_balance_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='current_balance',
            field=models.TextField(blank=True),
        ),
    ]
